### ISSUE TITLE
ConcurrentModificationException when send message to consumer

### ISSUE THREAD

**Issue by codelipenghui** [streamnative/pulsar#1367]
```
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$SubList.checkForComodification(ArrayList.java:1241) ~[?:1.8.0_265]
	at java.util.ArrayList$SubList.size(ArrayList.java:1050) ~[?:1.8.0_265]
	at org.apache.pulsar.broker.service.Consumer.lambda$sendMessages$0(Consumer.java:267) ~[org.apache.pulsar-pulsar-broker-2.6.0-sn-12.jar:2.6.0-sn-12]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387) [io.netty-netty-transport-native-epoll-4.1.48.Final-linux-x86_64.jar:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

**Comment by codelipenghui** [comment]
close via https://github.com/apache/pulsar/issues/7804
