### ISSUE TITLE
ISSUE-8524: encounter ClassNotFoundException when using master branch to create PulsarAdmin

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#1672]
Original Issue: apache/pulsar#8524 

---

**Describe the bug**
In order to use transaction to make exactly-once sink of pulsar-flink connector, I packaged the master branch of pulsar. When the dependency was imported to create pulsarAdmin, it happened `java.lang.ClassNotFoundException`

**To Reproduce**
1、Use `mvn clean install` to package pulsar master branch.
2、Create pulsarAdmin by 
`PulsarAdmin.builder().serviceHttpUrl(serviceURL).build();`
3、The error occurred

**Expected behavior**
Create pulsarAdmin correctly.

**Screenshots**
<img width="2310" alt="WeChat74aa2e2f90c1de949308c4a94f5d29df" src="https://user-images.githubusercontent.com/19502505/98830797-c502ca00-2475-11eb-8b82-efdcd52fc3a6.png">

**Desktop (please complete the following information):**
 - OS: macos
 - JDK: jdk1.8.0_271

**Additional context**
None.

**Comment by reswqa** [comment]
`Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/pulsar/shade/javax/annotation/Priority
	at org.apache.pulsar.shade.org.glassfish.jersey.model.internal.ComponentBag.modelFor(ComponentBag.java:529)
	at org.apache.pulsar.shade.org.glassfish.jersey.model.internal.ComponentBag.lambda$registerModel$10(ComponentBag.java:454)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.apache.pulsar.shade.org.glassfish.jersey.model.internal.ComponentBag.registerModel(ComponentBag.java:446)
	at org.apache.pulsar.shade.org.glassfish.jersey.model.internal.ComponentBag.register(ComponentBag.java:283)
	at org.apache.pulsar.shade.org.glassfish.jersey.model.internal.CommonConfig.register(CommonConfig.java:402)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientConfig$State.register(ClientConfig.java:215)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientConfig.register(ClientConfig.java:594)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyClientBuilder.register(JerseyClientBuilder.java:188)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyClientBuilder.register(JerseyClientBuilder.java:41)
	at org.apache.pulsar.client.admin.PulsarAdmin.<init>(PulsarAdmin.java:187)
	at org.apache.pulsar.client.admin.internal.PulsarAdminBuilderImpl.build(PulsarAdminBuilderImpl.java:46)
	at Test1.main(Test1.java:12)
Caused by: java.lang.ClassNotFoundException: org.apache.pulsar.shade.javax.annotation.Priority
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 15 more`
