### ISSUE TITLE
ISSUE-10903: PulsarStandalone throws error while creating Ledger

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#2636]
Original Issue: apache/pulsar#10903 

---

**Describe the bug**
I am using `pulsar-broker-shaded` dependency to create `PulsarStandalone` cluster locally. However, the cluster fails at startup with the following exception - 

```
java.io.IOException: Failed to instantiate ledger storage : org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage
	at org.apache.pulsar.shade.org.apache.bookkeeper.bookie.LedgerStorageFactory.createLedgerStorage(LedgerStorageFactory.java:35)
	at org.apache.pulsar.shade.org.apache.bookkeeper.bookie.Bookie.buildLedgerStorage(Bookie.java:637)
	at org.apache.pulsar.shade.org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:759)
	at org.apache.pulsar.shade.org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:152)
	at org.apache.pulsar.shade.org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:120)
	at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.runBookies(LocalBookkeeperEnsemble.java:302)
	at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.startStandalone(LocalBookkeeperEnsemble.java:430)
	at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:258)
	at org.kharekartik.Main.main(Main.java:39)
Caused by: java.lang.RuntimeException: org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage not org.apache.pulsar.shade.org.apache.bookkeeper.bookie.LedgerStorage
	at org.apache.pulsar.shade.org.apache.bookkeeper.common.util.ReflectionUtils.newInstance(ReflectionUtils.java:169)
	at org.apache.pulsar.shade.org.apache.bookkeeper.bookie.LedgerStorageFactory.createLedgerStorage(LedgerStorageFactory.java:33)
	... 8 more
```

The `pulsar-broker` unshaded dependency works correctly but I can't use it as it throws a lot of dependency convergence errors due to `maven enforcer` plugin. The plugin is present in parent pom and is mandatory so can't disable it.

**To Reproduce**

```java
final File clusterConfigFile = new File(Main.class.getClassLoader().getResource("standalone.conf").toURI());
    ServiceConfiguration config =
        PulsarConfigurationLoader.create((new FileInputStream(clusterConfigFile)), ServiceConfiguration.class);
    config.setManagedLedgerDefaultEnsembleSize(1);
    config.setManagedLedgerDefaultWriteQuorum(1);
    config.setManagedLedgerDefaultAckQuorum(1);
    String zkServers = "127.0.0.1";
    config.setAdvertisedAddress("localhost");

    PulsarStandalone
        pulsarStandalone = PulsarStandaloneBuilder.instance().withConfig(config).withNoStreamStorage(true).build();

    if (config.getZookeeperServers() != null) {
      pulsarStandalone.setZkPort(Integer.parseInt(config.getZookeeperServers().split(":")[1]));
    }

    config.setZookeeperServers(zkServers + ":" + pulsarStandalone.getZkPort());
    config.setConfigurationStoreServers(zkServers + ":" + pulsarStandalone.getZkPort());

    config.setRunningStandalone(true);

    pulsarStandalone.setConfigFile(clusterConfigFile.getAbsolutePath());
    pulsarStandalone.setConfig(config);

    pulsarStandalone.start();

    PulsarAdmin admin =
        PulsarAdmin.builder().serviceHttpUrl("http://localhost:" + config.getWebServicePort().get()).build();

    admin.topics().createPartitionedTopic("test-topic", 3);
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>pulsar-standalone-repro</artifactId>
  <version>1.0-SNAPSHOT</version>

  <properties>
    <pulsar.version>2.7.2</pulsar.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.apache.pulsar</groupId>
      <artifactId>pulsar-broker-shaded</artifactId>
      <version>${pulsar.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.pulsar</groupId>
          <artifactId>pulsar-client-original</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.pulsar</groupId>
          <artifactId>pulsar-client-admin-original</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.apache.pulsar</groupId>
      <artifactId>pulsar-client</artifactId>
      <version>${pulsar.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.pulsar</groupId>
      <artifactId>pulsar-client-admin</artifactId>
      <version>${pulsar.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>8</source>
          <target>8</target>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
```

The `standalone.conf` is the one supplied out of the box in pulsar package.

**Comment by KKcorps** [comment]
The above error is actually fixable by changing the following configuration in `standalone.conf`

```properties
ledgerStorageClass=org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage
```

to

```properties
ledgerStorageClass=org.apache.pulsar.shade.org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage
```

but after this the next error is due to RocksDB not being able to find java native methods

```
java.lang.UnsatisfiedLinkError: org.apache.pulsar.shade.org.rocksdb.WriteOptions.newWriteOptions()J
	at org.apache.pulsar.shade.org.rocksdb.WriteOptions.newWriteOptions(Native Method) ~[pulsar-broker-shaded-2.7.2.jar:2.7.2]
	at org.apache.pulsar.shade.org.rocksdb.WriteOptions.<init>(WriteOptions.java:19) ~[pulsar-broker-shaded-2.7.2.jar:2.7.2]
	at org.apache.pulsar.shade.org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.<init>(KeyValueStorageRocksDB.java:96) ~[pulsar-broker-shaded-2.7.2.jar:2.7.2]
	at org.apache.pulsar.shade.org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.<init>(KeyValueStorageRocksDB.java:85) ~[pulsar-broker-shaded-2.7.2.jar:2.7.2]
	at org.apache.pulsar.shade.org.apache.bookkeeper.bookie.storage.ldb.KeyValueStorageRocksDB.lambda$static$0(KeyValueStorageRocksDB.java:60) ~[pulsar-broker-shaded-2.7.2.jar:2.7.2]
	at org.apache.pulsar.shade.org.apache.bookkeeper.bookie.storage.ldb.LedgerMetadataIndex.<init>(LedgerMetadataIndex.java:70) ~[pulsar-broker-shaded-2.7.2.jar:2.7.2]
```

**Comment by KKcorps** [comment]
@sijie @polyzos Any update here?

**Comment by zymap** [comment]
Hi @KKcorps, Here has an example about how to start standalone: https://github.com/zymap/pulsar-learning

Looks like the shaded package is not recommend used in the maven project as a dependency, So I just use the original package and everything looks good to start a standalone service with code. 
https://stackoverflow.com/questions/13620281/what-is-the-maven-shade-plugin-used-for-and-why-would-you-want-to-relocate-java

**Comment by KKcorps** [comment]
Hi @zymap I am aware of this and already got it working with unshaded dependency. 
the problem is I don't want to use unshaded dependency in my program because then I have to do a lot of exclusions because of maven enforcer plugin

**Comment by zymap** [comment]
Hi @KKcorps . Sorry for that, I noticed that when I send out the comments.

The error looks like the rocksdb lib is not load properly and I am trying to figure out the reason.
I remembered that when generating a JNI method, the CPP code will make the package name as the method name. But when we shade the package, we change the package name. I am not sure if this related to the issue.

**Comment by zymap** [comment]
I tried to remove the rocksdb dependency from the shaded pom in the master code and the error is gone

**Comment by KKcorps** [comment]
Can you share your changes? I'll try it out on my end as well.

**Comment by zymap** [comment]
I removed all the rocksdb related in this file https://github.com/apache/pulsar/blob/81063c04870ba7fa26222e57e4d4e94145e0a1e0/pulsar-broker-shaded/pom.xml#L22.

**Comment by KKcorps** [comment]
Yes, the rocksDB error is gone now. but now I am getting this error
```
Caused by: java.lang.IllegalStateException: InjectionManagerFactory not found.
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:74) ~[pulsar-broker-shaded-2.9.0-SNAPSHOT.jar:2.9.0-SNAPSHOT]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_265]

```

**Comment by KKcorps** [comment]
Hi,
It is working now.
Had to make the following changes in pom
https://github.com/apache/pulsar/compare/v2.7.2...KKcorps:pulsar_broker_shaded_patch?expand=1
