### ISSUE TITLE
[proxy] [2.10.0.0-rc3] Proxy throws type conversion error on startup, won't start

### ISSUE THREAD

**Issue by utahkay** [streamnative/pulsar#3771]
**Describe the bug**
With release candidate 2.10.0.0-rc3, the proxy won't start. I'm testing in CloudHosted with cloud-pulsar image.

**To Reproduce**
1. Deploy a cloud hosted PulsarCluster with image `gcr.io/affable-ray-226821/pulsar-cloud@sha256:1d69e8fe5b6180f1d5d4e282b8b5561358e3b6336a0754c5b88fd7abda69b9c3`
2. Observe the proxy logs

**Expected behavior**
Expect the proxy to start up successfully

**Logs**
```
2022-02-16T17:56:26,370+0000 [main] ERROR org.apache.pulsar.proxy.server.ProxyServiceStarter - Failed to start pulsar proxy service. error msg failed to initialize zooKeeperCacheExpirySeconds field while setting value -1additionalServletDirectory=./proxyAdditionalServlet
java.lang.IllegalArgumentException: failed to initialize zooKeeperCacheExpirySeconds field while setting value -1additionalServletDirectory=./proxyAdditionalServlet
	at org.apache.pulsar.common.util.FieldParser.lambda$update$0(FieldParser.java:149) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at org.apache.pulsar.common.util.FieldParser.update(FieldParser.java:138) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.common.configuration.PulsarConfigurationLoader.create(PulsarConfigurationLoader.java:98) ~[io.streamnative-pulsar-broker-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.common.configuration.PulsarConfigurationLoader.create(PulsarConfigurationLoader.java:75) ~[io.streamnative-pulsar-broker-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.common.configuration.PulsarConfigurationLoader.create(PulsarConfigurationLoader.java:55) ~[io.streamnative-pulsar-broker-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.proxy.server.ProxyServiceStarter.<init>(ProxyServiceStarter.java:144) [io.streamnative-pulsar-proxy-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.proxy.server.ProxyServiceStarter.main(ProxyServiceStarter.java:184) [io.streamnative-pulsar-proxy-2.10.0.0-rc5.jar:2.10.0.0-rc5]
Caused by: java.lang.RuntimeException: Cannot convert from java.lang.String to java.lang.Integer. Conversion failed with null
	at org.apache.pulsar.common.util.FieldParser.convert(FieldParser.java:122) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.common.util.FieldParser.value(FieldParser.java:193) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.common.util.FieldParser.lambda$update$0(FieldParser.java:144) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.pulsar.common.util.FieldParser.convert(FieldParser.java:118) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.common.util.FieldParser.value(FieldParser.java:193) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.common.util.FieldParser.lambda$update$0(FieldParser.java:144) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	... 8 more
Caused by: java.lang.NumberFormatException: For input string: "-1additionalServletDirectory=./proxyAdditionalServlet"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
	at java.lang.Integer.valueOf(Integer.java:983) ~[?:?]
	at org.apache.pulsar.common.util.FieldParser.stringToInteger(FieldParser.java:265) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.pulsar.common.util.FieldParser.convert(FieldParser.java:118) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.common.util.FieldParser.value(FieldParser.java:193) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	at org.apache.pulsar.common.util.FieldParser.lambda$update$0(FieldParser.java:144) ~[io.streamnative-pulsar-common-2.10.0.0-rc5.jar:2.10.0.0-rc5]
	... 8 more
```

**Desktop (please complete the following information):**
 - Cloud Hosted

**Additional context**
Brokers, bookies, and zookeeper start up OK.

**Comment by utahkay** [comment]
Eron did some troubleshooting. The root cause appears to be that proxy.conf does not have a newline at end of file. In [this PR](https://github.com/streamnative/pulsar/commit/3e065718939d028a970c6b03b96da94e78217583#diff-f6021f4eb78412cb22fddd64b711e74ef794d071f45200a1997a9e682077895aR272)

**Comment by utahkay** [comment]
This was fixed by https://github.com/apache/pulsar/pull/14359
