### ISSUE TITLE
ISSUE-5899: Cannot import Python pulsar-client==2.4.2 on Mac Os Catalina 10.15.2

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#47]
Original Issue: apache/pulsar#5899 

---

**Describe the bug**
With correctly installed `libpulsar` and `protobuf` and pulsar-client 2.4.2 cannot import pulsar on Python 3.7.5. An attempt to import raises ```ImportError: dlopen(/tmp/check/.venv/lib/python3.7/site-packages/_pulsar.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/protobuf@2.6/lib/libprotobuf-lite.9.dylib```

**To Reproduce**
1. Run:
```
# python3 -V
Python 3.7.5
# python3
Python 3.7.5 (default, Dec 12 2019, 09:41:03)
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pulsar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/check/.venv/lib/python3.7/site-packages/pulsar/__init__.py", line 102, in <module>
    import _pulsar
ImportError: dlopen(/tmp/check/.venv/lib/python3.7/site-packages/_pulsar.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/protobuf@2.6/lib/libprotobuf-lite.9.dylib
  Referenced from: /tmp/check/.venv/lib/python3.7/site-packages/_pulsar.cpython-37m-darwin.so
  Reason: image not found
```

2. See the error

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.2

**Comment by bry00** [comment]
Current state of pulsar-client--2.4.2 on MacOs Catalina 10.15.2:
```bash
# python3
Python 3.7.5 (default, Dec 12 2019, 09:41:03)
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pulsar
Segmentation fault: 11
```
