### ISSUE TITLE
ISSUE-5449: function worker v2.4.1 issues on shared dependencies

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#51]
Original Issue: apache/pulsar#5449 

---

**Describe the bug**
We bumped our functions workers to v2.4.1 from v2.4.0 and the function which is using several dependencies can't boot because of the following stack:

```
13:10:51.038 [clevercloud/functions/accessLogsCleverCloudADCHaproxy-0] ERROR org.apache.pulsar.functions.instance.JavaInstanceRunnable - [clevercloud/functions/accessLogsCleverCloudADCHaproxy:0] Uncaught exception in Java Instance
java.lang.RuntimeException: User class constructor throws exception
        at org.apache.pulsar.functions.utils.Reflections.createInstance(Reflections.java:126) ~[org.apache.pulsar-pulsar-functions-utils-2.4.1.jar:2.4.1]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setupJavaInstance(JavaInstanceRunnable.java:189) ~[org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:234) [org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_192]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_192]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_192]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_192]
        at org.apache.pulsar.functions.utils.Reflections.createInstance(Reflections.java:118) ~[org.apache.pulsar-pulsar-functions-utils-2.4.1.jar:2.4.1]
        ... 3 more
Caused by: java.lang.LinkageError: ClassCastException: attempting to castjar:file:/pulsar/lib/javax.ws.rs-javax.ws.rs-api-2.1.jar!/javax/ws/rs/client/ClientBuilder.class to file:/tmp/pulsar-nar/pulsar-functions-0.1.0-SNAPSHOT.jar-unpacked/javax/ws/rs/client/ClientBuilder.class
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:81) ~[javax.ws.rs-javax.ws.rs-api-2.1.jar:2.1]
        at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:97) ~[javax.ws.rs-javax.ws.rs-api-2.1.jar:2.1]
        at com.clevercloud.pulsar.util.GeoIPAPI.updateDatabase(GeoIPAPI.java:101) ~[?:?]
        at com.clevercloud.pulsar.util.GeoIPAPI.<init>(GeoIPAPI.java:45) ~[?:?]
        at com.clevercloud.pulsar.function.ApplicationsAddonsHaproxyAccessLogs.<init>(ApplicationsAddonsHaproxyAccessLogs.java:28) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_192]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_192]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_192]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_192]
        at org.apache.pulsar.functions.utils.Reflections.createInstance(Reflections.java:118) ~[org.apache.pulsar-pulsar-functions-utils-2.4.1.jar:2.4.1]
        ... 3 more
13:10:51.047 [clevercloud/functions/accessLogsCleverCloudADCHaproxy-0] INFO  org.apache.pulsar.functions.instance.JavaInstanceRunnable - Closing instance
````

**Comment by KannarFr** [comment]
Hi @sijie, what is the current status of this issue?

**Comment by sijie** [comment]
@KannarFr it seems not to be triaged yet. Let me add it to our backlog and have one engineer look  into it.

**Comment by KannarFr** [comment]
@sijie wha t is the current status? Any news?

**Comment by KannarFr** [comment]
@yjshen Hi, what is the status of this issue? Can I help you?

**Comment by sijie** [comment]
@KannarFr I don't think we get a chance to address the issue. If you have time, are you willing to contribute a fix?
